#!/bin/bash
#SBATCH --job-name=Analysis
#SBATCH --partition=thin
#SBATCH --time=36:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=64
#SBATCH --hint=multithread
#SBATCH -o output-%j.out
#SBATCH -e error-%j.err
#SBATCH --exclusive

module purge
module load 2021
module load Python/3.9.5-GCCcore-10.3.0

source $HOME/sidmfits_env/bin/activate

python3 $HOME/SIDMPlots/sidmfit.py \
-n DML025N752SigmaVelDep100Anisotropic \
-o $HOME/SIDMPlots/output_data/ \
-f Halo_data_DML025N752SigmaVelDep100Anisotropic \
-fc Halo_data_DML025N752SigmaConstant00

#python3 $HOME/SIDMPlots/addsidmdata.py \
#-d /projects/0/einf180/Tango_sims/L025N752/DMONLY/SigmaVelDep60Anisotropic  \
#-s snapshot_0036.hdf5 \
#-c subhalo_0036.properties \
#-n DML025N752SigmaVelDep60Anisotropic \
#-o $HOME/SIDMPlots/Simulation_data/ \
#-f Tree_data_Satellites_DML025N752SigmaVelDep60Anisotropic

#python3 $HOME/SIDMPlots/sidmplots.py \
#-d /projects/0/einf180/Tango_sims/L025N752/DMONLY/SigmaVelDep60Anisotropic  \
#-s snapshot_0036.hdf5 \
#-c subhalo_0036.properties \
#-n DML025N752SigmaVelDep60 \
#-o $HOME/SIDMPlots/output_data/

